services:
  - type: web
    name: helpyoulearnsite
    env: python
    buildCommand: ./build.sh
    startCommand: cd helpyoulearnsite && gunicorn helpyoulearnsite.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: helpyoulearnsite_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: helpyoulearnsite.settings
      - key: DEBUG
        value: False

databases:
  - name: helpyoulearnsite_db
    databaseName: helpyoulearnsite
    user: helpyoulearnsite