# Generated by Django 3.1.14 on 2025-04-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('image', models.ImageField(upload_to='quiz_images/%Y/%m/%d/', verbose_name='图片')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
