# Generated by Django 3.1.14 on 2025-04-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_imagedescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='单词')),
                ('meaning', models.CharField(max_length=255, verbose_name='含义')),
                ('example', models.TextField(blank=True, verbose_name='例句')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词',
                'ordering': ['word'],
            },
        ),
    ]
