# Generated by Django 3.1.14 on 2025-04-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['language', 'word'], 'verbose_name': '词汇', 'verbose_name_plural': '词汇'},
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('en', '英文'), ('zh', '中文')], default='en', max_length=2, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100, verbose_name='词汇'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('word', 'language')},
        ),
    ]
